name: test mongo
on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev]
jobs:
  test-mongo-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.2.0, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.6.0
      - run: npm run build-tests
      - run: npm run test-mongo
  test-mongo-win:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.x, 16.2.0, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.6.0
      - run: npm run build-tests
      - run: npm run test-mongo
